-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) YEAR, MONTH(OS.SALES_DATE) MONTH, UI.GENDER, COUNT(DISTINCT OS.USER_ID) USERS
FROM USER_INFO UI, ONLINE_SALE OS
WHERE UI.USER_ID = OS.USER_ID AND UI.GENDER IS NOT NULL 
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3