# Write your MySQL query statement below
SELECT D.NAME DEPARTMENT, E.NAME EMPLOYEE, E.SALARY
FROM DEPARTMENT D, EMPLOYEE E
WHERE D.ID = E.DEPARTMENTID
AND E.SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE E WHERE D.ID = E.DEPARTMENTID)