-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * (1-P.DISCOUNT_RATE/100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN (SELECT H.CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
                WHERE MONTH(H.START_DATE) = 11 OR MONTH(H.END_DATE) = 11)
AND P.DURATION_TYPE = '30일 이상'
AND ROUND(C.DAILY_FEE * (1-P.DISCOUNT_RATE/100) * 30) >= 500000
AND ROUND(C.DAILY_FEE * (1-P.DISCOUNT_RATE/100) * 30) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC