# Write your MySQL query statement below
SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM (SELECT D.NAME DEPARTMENT,
      E.NAME EMPLOYEE,
      E.SALARY SALARY,
      DENSE_RANK() OVER(PARTITION BY D.NAME ORDER BY E.SALARY DESC) DRK
      FROM EMPLOYEE E
      LEFT JOIN DEPARTMENT D
      ON E.DEPARTMENTID = D.ID) A
WHERE A.DRK <= 3