-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT(OS.USER_ID)) AS PUCHASED_USERS,
ROUND(
    COUNT(DISTINCT(OS.USER_ID)) / 
    (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS OS
LEFT JOIN USER_INFO AS UI
ON OS.USER_ID = UI.USER_ID
WHERE YEAR(UI.JOINED) = 2021
GROUP BY 1, 2
ORDER BY 1, 2