# Write your MySQL query statement below
SELECT ID,
CASE
    WHEN ID % 2 = 0 THEN (SELECT STUDENT FROM SEAT WHERE ID = (S.ID - 1))
    WHEN ID % 2 = 1 AND ID < (SELECT COUNT(*) FROM SEAT) THEN (SELECT STUDENT FROM SEAT WHERE ID = (S.ID + 1))
    ELSE STUDENT END STUDENT
FROM SEAT S
ORDER BY 1