-- 코드를 입력하세요
WITH RECURSIVE TEMP AS (
SELECT 0 AS HOUR
UNION ALL
SELECT HOUR + 1 FROM TEMP
WHERE HOUR < 23)

SELECT HOUR, COUNT(ANIMAL_OUTS.DATETIME) AS COUNT FROM TEMP
LEFT JOIN ANIMAL_OUTS
ON TEMP.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOUR