# Write your MySQL query statement below
SELECT ID,
MAX(CASE WHEN MONTH = 'JAN' THEN REVENUE ELSE NULL END) JAN_REVENUE,
MAX(CASE WHEN MONTH = 'FEB' THEN REVENUE ELSE NULL END) FEB_REVENUE,
MAX(CASE WHEN MONTH = 'MAR' THEN REVENUE ELSE NULL END) MAR_REVENUE,
MAX(CASE WHEN MONTH = 'APR' THEN REVENUE ELSE NULL END) APR_REVENUE,
MAX(CASE WHEN MONTH = 'MAY' THEN REVENUE ELSE NULL END) MAY_REVENUE,
MAX(CASE WHEN MONTH = 'JUN' THEN REVENUE ELSE NULL END) JUN_REVENUE,
MAX(CASE WHEN MONTH = 'JUL' THEN REVENUE ELSE NULL END) JUL_REVENUE,
MAX(CASE WHEN MONTH = 'AUG' THEN REVENUE ELSE NULL END) AUG_REVENUE,
MAX(CASE WHEN MONTH = 'SEP' THEN REVENUE ELSE NULL END) SEP_REVENUE,
MAX(CASE WHEN MONTH = 'OCT' THEN REVENUE ELSE NULL END) OCT_REVENUE,
MAX(CASE WHEN MONTH = 'NOV' THEN REVENUE ELSE NULL END) NOV_REVENUE,
MAX(CASE WHEN MONTH = 'DEC' THEN REVENUE ELSE NULL END) DEC_REVENUE
FROM DEPARTMENT
GROUP BY 1