# Write your MySQL query statement below
SELECT U.USER_ID BUYER_ID, U.JOIN_DATE, COUNT(O.ORDER_DATE) ORDERS_IN_2019
FROM USERS U
LEFT JOIN ORDERS O
ON U.USER_ID = O.BUYER_ID AND YEAR(O.ORDER_DATE) = 2019
GROUP BY U.USER_ID