-- 코드를 입력하세요
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE A
LEFT JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.MEMBER_ID =
(SELECT MEMBER_ID FROM REST_REVIEW
      GROUP BY MEMBER_ID
      ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1)
ORDER BY 3, 2