-- 코드를 입력하세요
SELECT DISTINCT CAR_ID, '대여 가능' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE)
UNION
SELECT DISTINCT CAR_ID, '대여중' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT DISTINCT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE)
ORDER BY 1 DESC
