# Write your MySQL query statement below
SELECT T.REQUEST_AT AS 'DAY',
    ROUND(SUM(IF(STATUS != 'COMPLETED', 1, 0)) / COUNT(*), 2) AS 'CANCELLATION RATE'
FROM TRIPS T
WHERE T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
AND T.CLIENT_ID NOT IN (SELECT U.USERS_ID FROM USERS U WHERE U.BANNED = 'YES')
AND T.DRIVER_ID NOT IN (SELECT U.USERS_ID FROM USERS U WHERE U.BANNED = 'YES')
GROUP BY 1
ORDER BY 1