-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE*FO.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT FP, FOOD_ORDER FO
WHERE FP.PRODUCT_ID = FO.PRODUCT_ID AND MONTH(FO.PRODUCE_DATE)=5
GROUP BY 1
ORDER BY 3 DESC, 1